id: P90F72628
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS22941
  title: རྫོགས་པ་ཆེན་པོ་སེམས་ཉིད་ངལ་གསོའི་འགྲེལ་པ།
  volumes:
    0ab55996cd9e40a0a4923dbcc44af27a:
      image_group_id: I8LS22943
      title: ''
      base_file: v001.txt
  author: ''
